"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "os"
  style = "diamond"
  foreground = "#ffffff"
  background = "#0077c2"
  template = " {{ .Icon }}  "
  leading_diamond = ""
  trailing_diamond = " "

  [[blocks.segments]]
  type = "session"
  style = "diamond"
  foreground = "#ffffff"
  background = "#6a0dad"
  template = "{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} "
  powerline_symbol = ""

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  foreground = "#333333"
  background = "#ff479c"
  template = "  {{ if .Segments.Contains \"Git\" }}{{ .Segments.Git.RepoName }}{{ else }}{{ .Path }}{{ end }} "
  powerline_symbol = ""

    [blocks.segments.options]
    style = "folder"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  foreground = "#193549"
  background = "#fffb38"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FF{{ end }}"
]
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  powerline_symbol = ""

    [blocks.segments.options]
    fetch_status = true
    fetch_upstream_icon = true

  [[blocks.segments]]
  type = "status"
  style = "diamond"
  foreground = "#ffffff"
  background = "#2e9599"
  background_templates = [ "{{ if gt .Code 0 }}#f1184c{{ end }}" ]
  template = "  {{ if gt .Code 0 }} {{ reason .Code }}{{ else }}{{ end }} "
  leading_diamond = ""
  trailing_diamond = ""

    [blocks.segments.options]
    always_enabled = true

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  foreground = "#ffffff"
  background = "#575656"
  template = " <#f36943></> {{ .FormattedMs }} "

    [blocks.segments.options]
    threshold = 0
    style = "austin"

  [[blocks.segments]]
  type = "shell"
  style = "plain"
  foreground = "#ffffff"
  background = "#0077c2"
  template = "<#0077c2,transparent></>  {{ .Name }} <#2e9599,#0077c2></>"

  [[blocks.segments]]
  type = "battery"
  style = "powerline"
  foreground = "#ffffff"
  background = "#f36943"
  background_templates = [
  "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
  "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
  "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
]
  template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} "
  powerline_symbol = ""
  invert_powerline = true

    [blocks.segments.options]
    charged_icon = " "
    charging_icon = " "
    discharging_icon = " "

  [[blocks.segments]]
  type = "time"
  style = "diamond"
  foreground = "#111111"
  background = "#2e9599"
  template = "  {{ .CurrentDate | date .Format }} "
  leading_diamond = ""
  trailing_diamond = ""
  invert_powerline = true

    [blocks.segments.options]
    time_format = "Mon Jan 2 3:04"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "kubectl"
  style = "diamond"
  foreground = "#000000"
  background = "#ebcc34"
  template = "  {{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}} "
  leading_diamond = ""
  trailing_diamond = ""

  [[blocks.segments]]
  type = "az"
  style = "powerline"
  foreground = "#000000"
  background = "#9ec3f0"
  template = "{{ if matchP \"(?i)(azure|az-|-az)\" .PWD }}   •  {{.User.Name}}  {{ .Name }} {{ end }}"
  powerline_symbol = " "
  leading_diamond = ""
  trailing_diamond = ""

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#E06C75"
  template = "❯ "

[[tooltips]]
type = "node"
style = "diamond"
tips = [ "node", "npm", "yarn" ]
foreground = "#ffffff"
background = "#303030"
template = "  {{ .Full }} "
leading_diamond = ""
trailing_diamond = ""

[[tooltips]]
type = "terraform"
style = "diamond"
tips = [ "terraform", "tf" ]
foreground = "#000000"
background = "#d4fb7d"
template = " 󱁢 {{ .Version }} "
leading_diamond = ""
trailing_diamond = ""

[[tooltips]]
type = "git"
style = "plain"
tips = [ "git", "g" ]
template = " {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }} "
foreground = "#ffffff"
background = "#193549"

[transient_prompt]
background = "transparent"
foreground = "#E06C75"
template = "❯ "
